### ISSUE TITLE
 Navkey.js not working , can't use arrow keys to navigate #30 

### ISSUE THREAD

**Issue by LunaP** [Frumph/comicpress#33]
Since the previous case was closed without any assistance I'm reopening it here.

Using the latest Comicpress 4.2.2 and noticed that the arrow keys aren't allowing for navigation.
I've checked the settings under comic config, and comicpress config. Its active.

I tried calling the js manually but no go. Any ideas or suggestions on how I could troubleshoot this? Tried reinstalling a few times no dice.

In response to Frumph ( 2 months later )

Doesn't work in Chrome/Firefox/palemoon/IE/opera. I'm running windows, and haven't verified with anyone running linux. Any reason this was closed? Any troubleshooting tips you could suggest? Hoping it won't take another 2 months to respond.

**Comment by Frumph** [comment]
... comicpress does not have a navkey.js - 

https://github.com/Frumph/comic-easel/issues

Tested under windows with Chrome/FireFox/IE(Edge) - all working

I suggest disabling all plugins except comic easel and see if it executes properly - otherwise get the 'firebug' addon for firefox, hit F10 and set it up for script checking - enabled - refresh your page and see if it comes up with errors
